GET http://localhost:3000/events

###
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Evento-1",
  "description": "Evento 1 | Lançamento",
  "date": "2024-06-18T00:00:00.000Z",
  "price": 23
}